Repository uplus-3/backend, pull requests merged in 2022-08, with the labels that each got.

#5 ✨ Device MVP API & 통합 테스트 구현
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/dto/ColorResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponsetDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceSelfCompResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ImageResponseDto.java
  src/main/java/com/uplus/backend/device/dto/TagResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/device/exception/DeviceException.java
  src/main/java/com/uplus/backend/device/exception/DeviceExceptionHandler.java
  src/main/java/com/uplus/backend/device/repository/ColorRepository.java
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/device/repository/ImageRepository.java
  src/main/java/com/uplus/backend/device/repository/TagRepository.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/main/java/com/uplus/backend/global/util/DiscountUtil.java
  src/main/java/com/uplus/backend/global/util/Util.java
  src/main/java/com/uplus/backend/plan/dto/PlanDetailResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/plan/repository/PlanRepository.java
  src/main/java/com/uplus/backend/support/controller/SupportController.java
  src/main/java/com/uplus/backend/support/dto/SupportResponsetDto.java
  src/main/java/com/uplus/backend/support/exception/SupportException.java
  src/main/java/com/uplus/backend/support/repository/SupportRepository.java
  src/main/java/com/uplus/backend/support/service/SupportService.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/resources/application.yml
Labels: :sparkles: Feature

#7 Feat/i6 Order, Search, Plan API 구현
  build.gradle
  src/main/java/com/uplus/backend/device/dto/ImageResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/order/controller/OrderController.java
  src/main/java/com/uplus/backend/order/dto/OrderCreateRequestDto.java
  src/main/java/com/uplus/backend/order/dto/OrderCreateResponsetDto.java
  src/main/java/com/uplus/backend/order/dto/OrderResponseDto.java
  src/main/java/com/uplus/backend/order/dto/OrderResponsetDto.java
  src/main/java/com/uplus/backend/order/entity/Order.java
  src/main/java/com/uplus/backend/order/repository/OrderRepository.java
  src/main/java/com/uplus/backend/order/service/OrderService.java
  src/main/java/com/uplus/backend/plan/controller/PlanController.java
  src/main/java/com/uplus/backend/plan/dto/PlanListResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/planResponsetDto.java
  src/main/java/com/uplus/backend/plan/repository/PlanRepository.java
  src/main/java/com/uplus/backend/plan/service/PlanService.java
  src/main/java/com/uplus/backend/search/controller/SearchController.java
  src/main/java/com/uplus/backend/search/dto/SearchListResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponsetDto.java
  src/main/java/com/uplus/backend/search/service/SearchService.java
Labels: :sparkles: Feature

#9 ♻️ 엔터티 수정
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/global/entity/BaseEntity.java
  src/main/java/com/uplus/backend/order/dto/OrderResponseDto.java
  src/main/java/com/uplus/backend/order/entity/Order.java
  src/main/java/com/uplus/backend/plan/dto/PlanListResponseDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/resources/application-db.yml
Labels: :recycle: Refactor

#12 :white_check_mark: Device MVP 단위 테스트 작성
  src/main/java/com/uplus/backend/device/dto/ImageResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/DeviceRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/device/DeviceServiceUnitTest.java
Labels: :white_check_mark: Test

#18 ✨ Entity 생성 API 추가
  src/main/java/com/uplus/backend/device/controller/ColorController.java
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/controller/ImageController.java
  src/main/java/com/uplus/backend/device/controller/TagController.java
  src/main/java/com/uplus/backend/device/dto/ColorCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/ColorCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ImageCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/ImageCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/TagCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/TagCreateResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/device/service/ColorService.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/main/java/com/uplus/backend/device/service/ImageService.java
  src/main/java/com/uplus/backend/device/service/TagService.java
  src/main/java/com/uplus/backend/global/entity/BaseEntity.java
  src/main/java/com/uplus/backend/global/util/DiscountUtil.java
  src/main/java/com/uplus/backend/global/util/PriceUtil.java
  src/main/java/com/uplus/backend/order/entity/Order.java
  src/main/java/com/uplus/backend/plan/controller/PlanController.java
  src/main/java/com/uplus/backend/plan/dto/PlanCreateRequestDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanCreateResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanDetailResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/plan/service/PlanService.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/repository/DeviceRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/device/repository/TagRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/device/service/DeviceServiceUnitTest.java
Labels: :sparkles: Feature

#20 ✨ Search API 구현
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/global/util/OrderNumberUtil.java
  src/main/java/com/uplus/backend/order/dto/OrderCreateRequestDto.java
  src/main/java/com/uplus/backend/order/repository/OrderRepository.java
  src/main/java/com/uplus/backend/order/service/OrderService.java
  src/main/java/com/uplus/backend/plan/controller/PlanController.java
  src/main/java/com/uplus/backend/plan/dto/PlanListResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanResponseDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/plan/repository/PlanRepository.java
  src/main/java/com/uplus/backend/plan/service/PlanService.java
  src/main/java/com/uplus/backend/search/controller/SearchController.java
  src/main/java/com/uplus/backend/search/dto/SearchKeywordListResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchKeywordResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchListResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/main/java/com/uplus/backend/search/service/SearchService.java
  src/test/java/com/uplus/backend/integration/order/OrderIntegrationTest.java
  src/test/java/com/uplus/backend/integration/plan/PlanIntegrationTest.java
  src/test/java/com/uplus/backend/integration/search/SearchIntegrationTest.java
Labels: :sparkles: Feature

#23 :white_check_mark: 테스트 코드 수정 (PR merge CD 테스트)
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
Labels: :recycle: Refactor

#24 ✅ Plan, Order, Search Test Code 작성
  .gitignore
  src/main/java/com/uplus/backend/global/entity/BaseEntity.java
  src/main/java/com/uplus/backend/global/util/OrderNumberUtil.java
  src/main/java/com/uplus/backend/order/repository/OrderRepository.java
  src/main/java/com/uplus/backend/order/service/OrderService.java
  src/main/java/com/uplus/backend/plan/dto/PlanListResponseDto.java
  src/main/java/com/uplus/backend/search/controller/SearchController.java
  src/main/java/com/uplus/backend/search/service/SearchService.java
  src/test/java/com/uplus/backend/integration/order/OrderIntegrationTest.java
  src/test/java/com/uplus/backend/integration/search/SearchIntegrationTest.java
  src/test/java/com/uplus/backend/unit/order/controller/OrderControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/order/repository/OrderRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/order/service/OrderServiceUnitTest.java
  src/test/java/com/uplus/backend/unit/plan/controller/PlanControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/plan/repository/PlanRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/plan/service/PlanServiceUnitTest.java
  src/test/java/com/uplus/backend/unit/search/controller/SearchControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/search/service/SearchServiceUnitTest.java
Labels: :white_check_mark: Test

#26 ♻️ response 시리얼 번호 추가, 스웨거 작성
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/dto/ColorCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/ColorCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ColorResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ImageCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/TagCreateRequestDto.java
Labels: :recycle: Refactor

#28 ♻️ dto swagger 수정
  src/main/java/com/uplus/backend/device/dto/DeviceSelfCompResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ImageCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/ImageCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/ImageResponseDto.java
  src/main/java/com/uplus/backend/device/dto/TagCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/TagCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/TagResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/order/service/OrderService.java
  src/main/java/com/uplus/backend/plan/dto/PlanCreateRequestDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanCreateResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanDetailResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanListResponseDto.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchKeywordListResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchListResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/integration/order/OrderIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/repository/DeviceRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/device/service/DeviceServiceUnitTest.java
  src/test/java/com/uplus/backend/unit/order/controller/OrderControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/order/service/OrderServiceUnitTest.java
  src/test/java/com/uplus/backend/unit/search/controller/SearchControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/search/service/SearchServiceUnitTest.java
Labels: :recycle: Refactor

#30 :sparkles: dto, entity validation 구현(#29)
  src/main/java/com/uplus/backend/device/dto/DeviceCreateRequestDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/global/util/OrderNumberUtil.java
  src/main/java/com/uplus/backend/order/dto/OrderCreateRequestDto.java
  src/main/java/com/uplus/backend/order/entity/Order.java
  src/main/java/com/uplus/backend/plan/dto/PlanCreateRequestDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/test/java/com/uplus/backend/integration/order/OrderIntegrationTest.java
Labels: :sparkles: Feature

#33 :recycle: 연관관계, device 조회 리팩토링
  src/main/java/com/uplus/backend/device/controller/ColorController.java
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/controller/ImageController.java
  src/main/java/com/uplus/backend/device/controller/TagController.java
  src/main/java/com/uplus/backend/device/dto/ColorCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceSelfCompResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/main/java/com/uplus/backend/global/config/WebMvcConfig.java
  src/main/java/com/uplus/backend/global/exception/ErrorCode.java
  src/main/java/com/uplus/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/uplus/backend/global/util/PriceUtil.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
Labels: :recycle: Refactor

#34 :sparkles: Plan, Order, Search exception 처리 및 로직 수정(#32)
  src/main/java/com/uplus/backend/device/service/ColorService.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/main/java/com/uplus/backend/device/service/ImageService.java
  src/main/java/com/uplus/backend/device/service/TagService.java
  src/main/java/com/uplus/backend/global/config/WebMvcConfig.java
  src/main/java/com/uplus/backend/global/exception/ErrorCode.java
  src/main/java/com/uplus/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/uplus/backend/global/util/OrderNumberUtil.java
  src/main/java/com/uplus/backend/global/util/PriceUtil.java
  src/main/java/com/uplus/backend/order/service/OrderService.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
  src/main/java/com/uplus/backend/plan/service/PlanService.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/main/java/com/uplus/backend/search/service/SearchService.java
Labels: :sparkles: Feature

#37 ♻️ 1의 자릿수 버림, 가격 로직 리팩토링
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/global/util/PriceUtil.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
Labels: :recycle: Refactor

#39 ✨ 검색 full text search 적용
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/global/exception/ErrorCode.java
  src/main/java/com/uplus/backend/global/util/QueryUtil.java
  src/main/java/com/uplus/backend/search/dto/SearchKeywordResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/main/java/com/uplus/backend/search/service/SearchService.java
  src/test/java/com/uplus/backend/integration/search/SearchIntegrationTest.java
  src/test/java/com/uplus/backend/unit/search/service/SearchServiceUnitTest.java
  src/test/resources/application-db.yml
Labels: :sparkles: Feature

#40 :recycle: 단말기 리스트, 가격 API 분리
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/dto/ColorRepResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/PriceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/PriceResponseDto.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/main/java/com/uplus/backend/global/util/PriceUtil.java
  src/main/java/com/uplus/backend/plan/dto/PlanPriceResponseDto.java
  src/main/java/com/uplus/backend/search/dto/SearchResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/service/DeviceServiceUnitTest.java
Labels: :recycle: Refactor
