Repository uplus-3/backend, pull requests merged in 2022-09, with the labels that each got.

#46 :recycle: DeviceResponseDto 수정
  src/main/java/com/uplus/backend/device/dto/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/PriceResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
Labels: :recycle: Refactor

#48 [FEAT] 출시 예정 단말기 조회 API 구현
  src/main/java/com/uplus/backend/launchingdevice/controller/LaunchingDeviceController.java
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingColorResponseDto.java
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingDeviceListRequestDto.java
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingDeviceListResponseDto.java
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingDeviceResponseDto.java
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingImageResponseDto.java
  src/main/java/com/uplus/backend/launchingdevice/entity/LaunchingColor.java
  src/main/java/com/uplus/backend/launchingdevice/entity/LaunchingDevice.java
  src/main/java/com/uplus/backend/launchingdevice/entity/LaunchingImage.java
  src/main/java/com/uplus/backend/launchingdevice/repository/LaunchingColorRepository.java
  src/main/java/com/uplus/backend/launchingdevice/repository/LaunchingDeviceRepository.java
  src/main/java/com/uplus/backend/launchingdevice/repository/LaunchingImageRepository.java
  src/main/java/com/uplus/backend/launchingdevice/service/LaunchingDeviceService.java
  src/test/java/com/uplus/backend/integration/launchingdevice/LaunchingDeviceIntegrationTest.java
Labels: :sparkles: Feature

#55 :sparkles: 단말기 심플 리스트 조회 API 추가
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/dto/DeviceSimpleListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/DeviceSimpleResponseDto.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
Labels: :sparkles: Feature

#58 :recycle: Device에 쿼리 최적화를 위한 fetch EAGER 추가
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
Labels: :recycle: Refactor

#60 :recycle: dto 패키지 분리
  src/main/java/com/uplus/backend/device/controller/DeviceController.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceCreateRequestDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceCreateResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceSelfCompResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceSimpleListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/device/DeviceSimpleResponseDto.java
  src/main/java/com/uplus/backend/device/dto/price/PriceDetailResponseDto.java
  src/main/java/com/uplus/backend/device/dto/price/PriceListResponseDto.java
  src/main/java/com/uplus/backend/device/dto/price/PriceResponseDto.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/service/DeviceServiceUnitTest.java
Labels: :recycle: Refactor

#53 ✨ 카트기능 구현
  src/main/java/com/uplus/backend/cart/controller/CartController.java
  src/main/java/com/uplus/backend/cart/dto/CartListResponseDto.java
  src/main/java/com/uplus/backend/cart/dto/CartRequestDto.java
  src/main/java/com/uplus/backend/cart/dto/CartResponseDto.java
  src/main/java/com/uplus/backend/cart/entity/Cart.java
  src/main/java/com/uplus/backend/cart/exception/CartException.java
  src/main/java/com/uplus/backend/cart/repository/CartRepository.java
  src/main/java/com/uplus/backend/cart/service/CartService.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/global/exception/ErrorCode.java
  src/main/java/com/uplus/backend/global/util/CartIdUtil.java
  src/main/java/com/uplus/backend/plan/entity/Plan.java
Labels: :sparkles: Feature

#63 ♻️ Device 조회 쿼리 개선
  src/main/java/com/uplus/backend/device/dto/color/ColorRepResponseDto.java
  src/main/java/com/uplus/backend/device/entity/Color.java
  src/main/java/com/uplus/backend/device/entity/Device.java
  src/main/java/com/uplus/backend/device/entity/Image.java
  src/main/java/com/uplus/backend/device/entity/Tag.java
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/device/service/DeviceService.java
  src/test/java/com/uplus/backend/unit/device/service/DeviceServiceUnitTest.java
Labels: :recycle: Refactor

#66 :recycle: LaunchingDeviceResponseDto 수정
  src/main/java/com/uplus/backend/launchingdevice/dto/LaunchingDeviceResponseDto.java
Labels: :recycle: Refactor

#61 :sparkles: 빈 장바구니 조회 시 에러처리
  src/main/java/com/uplus/backend/cart/controller/CartController.java
  src/main/java/com/uplus/backend/cart/dto/CartRequestDto.java
  src/main/java/com/uplus/backend/cart/service/CartService.java
Labels: :sparkles: Feature, :bug: Bug

#70 :recycle: device response dto 수정
  src/main/java/com/uplus/backend/device/dto/color/ColorRepResponseDto.java
  src/main/java/com/uplus/backend/device/dto/price/PriceDetailResponseDto.java
Labels: :recycle: Refactor

#72 :white_check_mark: Order, Plan, Search 예외 Test Code 구현
  src/main/java/com/uplus/backend/order/controller/OrderController.java
  src/test/java/com/uplus/backend/integration/order/OrderIntegrationTest.java
  src/test/java/com/uplus/backend/integration/plan/PlanIntegrationTest.java
  src/test/java/com/uplus/backend/unit/order/controller/OrderControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/order/repository/OrderRepositoryUnitTest.java
  src/test/java/com/uplus/backend/unit/order/service/OrderServiceUnitTest.java
  src/test/java/com/uplus/backend/unit/plan/controller/PlanControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/search/controller/SearchControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/search/service/SearchServiceUnitTest.java
Labels: :white_check_mark: Test

#76 :sparkles: 검색 기능 수정
  src/main/java/com/uplus/backend/device/repository/DeviceRepository.java
  src/main/java/com/uplus/backend/global/util/QueryUtil.java
Labels: :sparkles: Feature

#74 :recycle: 장바구니 구현방식 변경
  src/main/java/com/uplus/backend/cart/controller/CartController.java
Labels: :recycle: Refactor

#82 :white_check_mark: Device 통합, 단위(컨트롤러, 레파지토리) 테스트 작성
  src/main/java/com/uplus/backend/device/dto/device/DeviceDetailResponseDto.java
  src/test/java/com/uplus/backend/integration/device/DeviceIntegrationTest.java
  src/test/java/com/uplus/backend/unit/device/controller/DeviceControllerUnitTest.java
  src/test/java/com/uplus/backend/unit/device/repository/DeviceRepositoryUnitTest.java
Labels: :white_check_mark: Test
